name: python 
on: push
jobs: 
  test: 
    runs-on: ubontu-latest
    steps: 
      - uses: actions/checkout@v2  
      - run: python Hello.py  
  build:
    needs: [test]
    runs-on: ubontu-latest
    steps:  
       - uses: actions/checkout@v2  
       - uses: actions/upload-artifact@v2
         with: 
            name: Hello
            path: .
